- name: Common tool setup on all the servers
  hosts: localhost
  become: yes
  vars:
    tom_url: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.86/bin/apache-tomcat-9.0.86.tar.gz

  tasks:
    - name: Install JDK on Ubuntu 22
      apt:
        name: default-jdk
        state: present
        update_cache: yes
      when: ansible_distribution == 'Ubuntu' 

    - name: Download Tomcat Tar Ball/Binaries
      get_url:
        url: "{{tom_url}}"
        dest: /tmp/tomcat-9.tar.gz

    - name: Add tomcat group
      group:
        name: tomcat
        state: present

    - name: Add tomcat user
      user:
        name: tomcat
        group: tomcat
        shell: /bin/nologin
        home: /usr/local/tomcat8

    - file:
        path: /tmp/tomcat8
        state: directory

    - name: Extract tomcat
      unarchive:
        src: /tmp/tomcat-9.tar.gz
        dest: /tmp/tomcat9/
        remote_src: yes
        list_files: yes
      register: unarchive_info

    - debug:
        msg: "{{unarchive_info.files[0].split('/')[0]}}"

    - name: Synchronize /tmp/tomcat9/tomcat_cont /usr/local/tomcat9.
      synchronize:
        src: "/tmp/tomcat9/{{unarchive_info.files[0].split('/')[0]}}/"
        dest: /usr/local/tomcat9/
      delegate_to: "{{ inventory_hostname }}"

    - name: Change ownership of /usr/local/tomcat9
      file:
        path: /usr/local/tomcat9
        owner: tomcat
        group: tomcat
        recurse: yes

    - name: Setup tomcat SVC file on Centos 7
      template:
         src: templates/epel7-svcfile.j2
         dest: /etc/systemd/system/tomcat.service
         mode: "a+x"
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'      

    - name: Setup tomcat SVC file on ubuntu 22
      template:
         src: templates/ubuntu22-svcfile.j2
         dest: /etc/systemd/system/tomcat.service
         mode: "a+x"
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version >= '22'

    - name: Reload tomcat svc config in ubuntu 22
      command: update-rc.d tomcat defaults
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version < '22'

    - name: just force systemd to reread configs (2.4 and above)
      systemd:
        daemon_reload: yes 
      when: ansible_distribution_major_version > '20' 

    - name: Start & Enable TOmcat 9
      service:
        name: tomcat
        state: started
        enabled: yes

   
